name: james potter

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: idaholab/moose

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
          echo "Running tests inside the container"

      - name: Run Tests
        run: |
          cd ../
          chmod +x run_test_cases.sh
          ./run_test_cases.sh
