name: james potter

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: idaholab/moose-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: eigen3 install
      run: |
        yum install -y eigen3-devel
      - name: pre_stage
        run: |
          export PATH="/opt/libmesh/bin:$PATH"
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
          echo "Running tests inside the container"

      - name: Run Tests
        run: |
          source ./run_test_cases.sh
