name: james potter

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: idaholab/moose-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        shell: bash
        run: |
          export CMAKE_PREFIX_PATH="/opt/libmesh:${CMAKE_PREFIX_PATH}"
          export PATH="/opt/libmesh/include:$PATH"         
          source /environment
          mkdir build
          cd build
          cmake ..
          make
          echo "Running tests inside the container"

      - name: Run Tests
        shell: bash
        run: |
          source ./run_test_cases.sh
