name: james potter

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: idaholab/moose-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Eigen3
        run: |
          yum install -y eigen3-devel

      - name: Pre-stage setup
        run: |
          export PATH="/opt/libmesh/bin:$PATH"
          export PATH="/opt/openmpi/bin:$PATH"
          which mpicxx
          mkdir build
          cd build
          cmake ..
          make
          echo "Running tests inside the container"

      - name: Run Tests
        run: |
          source ./run_test_cases.sh
