name: Tests
on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: moose
          condarc: |
            channels:
              - conda-forge
              - https://conda.software.inl.gov/public
          init-shell: bash
          create-args: moose-dev

      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake ..
          make
          echo "Running tests inside the container"

      - name: Run Tests
        shell: bash
        run: |
          source ./run_test_cases.sh